import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { useDispatch, useSelector } from 'react-redux'
import axios from 'axios'
import { motherNode } from '../d'
import { useEffect } from 'react'
import { updateNodeSystem } from '../feautures/node/nodeSlice'
import Sidebar from '../components/sidebar/Sidebar'
import FileEditors from '../components/file-editing/FileEditors'
import { RootState } from '../feautures/store'

export default function Home({motherNode}: {motherNode: motherNode}) {
  const {openFile} = useSelector((state: RootState) => state.editor)

  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(updateNodeSystem(motherNode))
  }, [motherNode])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar/>
      <FileEditors />
    </div>
  )
}

export async function getServerSideProps(){
  try {
    const motherNode = await axios.get<{motherNode: {motherNode: motherNode}}>(process.env.NEXT_PUBLIC_API_URL + 'node')
    return {
      props:{
        motherNode: motherNode.data.motherNode
      }
    }
    
  } catch (error) {
    console.error(error);
  }
}